apiServer:
  port: 8080
  publicScheme: http
  publicHost: localhost
  publicPort: 8080
  httpAllowOrigin: '*'

insightsServer:
  port: 8081
  publicScheme: http
  publicHost: localhost
  publicPort: 8081

webServer:
  port: 8082
  publicScheme: http
  publicHost: localhost
  publicPort: 8082

database:
  host: localhost
  port: 5432
  name: pixorama
  user: postgres
