apiServer:
  port: 8080
  publicScheme: https
  publicHost: ${PUBLIC_HOST}
  publicPort: 443

insightsServer:
  port: 8081
  publicScheme: https
  publicHost: ${PUBLIC_HOST}
  publicPort: 443

webServer:
  port: 8082
  publicScheme: https
  publicHost: ${PUBLIC_HOST}
  publicPort: 443

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
