apiServer:
  port: 8000
  publicScheme: https
  publicHost: pixorama-julian.koyeb.app
  publicPort: 443

insightsServer:
  port: 8001
  publicScheme: https
  publicHost: pixorama-julian.koyeb.app
  publicPort: 443

webServer:
  port: 8002

  publicScheme: https
  publicHost: pixorama-julian.koyeb.app
  publicPort: 443

database:
  host: ep-snowy-wave-a11bycwy-pooler.ap-southeast-1.aws.neon.tech
  port: 5432
  name: neondb
  user: neondb_owner
  requireSsl: true



